Started by user [8mha:////4AvbKtqCpWGC4/9vlaAOyQD+y56HOfLOpPpkD7K9YRsAAAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzWEgZu/dLi1CL9xJTczDwAj6GcLcAAAAA=[0madmin
Running as SYSTEM
Building in workspace /var/root/.jenkins/workspace/data-shuochang
using credential root
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@github.com:kirinisland/datapipe.git # timeout=10
Fetching upstream changes from git@github.com:kirinisland/datapipe.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git fetch --tags --force --progress -- git@github.com:kirinisland/datapipe.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision ca49a7d2f48e4a31b3d0bda9a079340aef4fd65b (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f ca49a7d2f48e4a31b3d0bda9a079340aef4fd65b # timeout=10
Commit message: "update sleep time back"
 > git rev-list --no-walk 26f9cd18d83485951213035c26aba7671df4f4b2 # timeout=10
[data-shuochang] $ /bin/sh -xe /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/jenkins4387279496585328907.sh
+ python3 runner_qq.py --method search --query $'\350\257\264\345\224\261' --output-suffix shuochang --dump-raw 1 --dump-seg 0 --proxy
INFO:[DataPipeline]:Start crawling for query: è¯´å”±
INFO:[DataPipeline]:Processing playlist page: 0, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 1, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 2, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 3, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 4, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 5, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 6, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 7, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 8, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 9, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 10, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 11, found 46 playlists
INFO:[DataPipeline]:Processing playlist page: 12, found 44 playlists
INFO:[DataPipeline]:Processing playlist page: 13, found 46 playlists
INFO:[DataPipeline]:Processing playlist page: 14, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 15, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 16, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 17, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 18, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 19, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 20, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 21, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 22, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 23, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 24, found 29 playlists
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "/Library/Python/3.7/site-packages/urllib3/connection.py", line 308, in connect
    self._tunnel()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 911, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 502 Proxy Error: server_error Error creating ext request: Connection closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Python/3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /soso/fcgi-bin/client_music_search_songlist?remoteplace=txt.yqq.playlist&searchid=122508096745936517&flag_qc=0&page_no=25&num_per_page=50&query=%E8%AF%B4%E5%94%B1&g_tk=5381&loginUin=0&hostUin=0&format=json&inCharset=utf8&outCharset=utf-8&notice=0&platform=yqq.json&needNewCode=0 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 502 Proxy Error: server_error Error creating ext request: Connection closed')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner_qq.py", line 158, in <module>
    main()
  File "runner_qq.py", line 140, in main
    playlists = get_playlists_by_query(args.query, args.limit, args.proxy, logger)
  File "runner_qq.py", line 21, in get_playlists_by_query
    lists = qq.search_by_query(query, page_number, limit)
  File "/private/var/root/.jenkins/workspace/data-shuochang/dao/qq_api.py", line 17, in search_by_query
    lists = self.fetch(url).get("data", {}).get("list", [])
  File "/private/var/root/.jenkins/workspace/data-shuochang/dao/base_api.py", line 29, in fetch
    verify=False)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /soso/fcgi-bin/client_music_search_songlist?remoteplace=txt.yqq.playlist&searchid=122508096745936517&flag_qc=0&page_no=25&num_per_page=50&query=%E8%AF%B4%E5%94%B1&g_tk=5381&loginUin=0&hostUin=0&format=json&inCharset=utf8&outCharset=utf-8&notice=0&platform=yqq.json&needNewCode=0 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 502 Proxy Error: server_error Error creating ext request: Connection closed')))
Build step 'Execute shell' marked build as failure
Finished: FAILURE
