Started by timer
Running as SYSTEM
Building in workspace /var/root/.jenkins/workspace/hot_user
using credential root
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@github.com:kirinisland/zaoci-tool.git # timeout=10
Fetching upstream changes from git@github.com:kirinisland/zaoci-tool.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git fetch --tags --force --progress -- git@github.com:kirinisland/zaoci-tool.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 67503715f5806fd7cdba1c9803cb59378dd4d097 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 67503715f5806fd7cdba1c9803cb59378dd4d097 # timeout=10
Commit message: "added UserIdentity table"
 > git rev-list --no-walk 67503715f5806fd7cdba1c9803cb59378dd4d097 # timeout=10
[hot_user] $ /bin/sh -xe /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/jenkins9054314471298211076.sh
+ python3 jobs/hot_user.py --count 25
Hot users after date: 2020-12-16 00:00:00
点赞最多: https://api2.bmob.cn/1/classes/EverydayLyric?&limit=25&where={"validStatus": {"$gte": 2, "$lte": 3}, "createdAt": {"$gte": {"__type": "Date", "iso": "2020-12-16 00:00:00"}}}&keys=user,likeCount,commentCount,bookmarkCount&order=-likeCount
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/Library/Python/3.7/site-packages/urllib3/connection.py", line 360, in connect
    ssl_context=context,
  File "/Library/Python/3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Python/3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api2.bmob.cn', port=443): Max retries exceeded with url: /1/classes/EverydayLyric?&limit=25&where=%7B%22validStatus%22:%20%7B%22$gte%22:%202,%20%22$lte%22:%203%7D,%20%22createdAt%22:%20%7B%22$gte%22:%20%7B%22__type%22:%20%22Date%22,%20%22iso%22:%20%222020-12-16%2000:00:00%22%7D%7D%7D&keys=user,likeCount,commentCount,bookmarkCount&order=-likeCount (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jobs/hot_user.py", line 170, in <module>
    main()
  File "jobs/hot_user.py", line 74, in main
    like_most_users = fetch_hot_users(like_url, headers)
  File "jobs/hot_user.py", line 113, in fetch_hot_users
    raw = requests.get(url, headers=headers)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api2.bmob.cn', port=443): Max retries exceeded with url: /1/classes/EverydayLyric?&limit=25&where=%7B%22validStatus%22:%20%7B%22$gte%22:%202,%20%22$lte%22:%203%7D,%20%22createdAt%22:%20%7B%22$gte%22:%20%7B%22__type%22:%20%22Date%22,%20%22iso%22:%20%222020-12-16%2000:00:00%22%7D%7D%7D&keys=user,likeCount,commentCount,bookmarkCount&order=-likeCount (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1056)')))
Build step 'Execute shell' marked build as failure
Finished: FAILURE
