Started by user [8mha:////4AvbKtqCpWGC4/9vlaAOyQD+y56HOfLOpPpkD7K9YRsAAAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzWEgZu/dLi1CL9xJTczDwAj6GcLcAAAAA=[0madmin
Running as SYSTEM
Building in workspace /var/root/.jenkins/workspace/data-zhongguofeng
using credential root
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@github.com:kirinisland/datapipe.git # timeout=10
Fetching upstream changes from git@github.com:kirinisland/datapipe.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git fetch --tags --force --progress -- git@github.com:kirinisland/datapipe.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 26f9cd18d83485951213035c26aba7671df4f4b2 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 26f9cd18d83485951213035c26aba7671df4f4b2 # timeout=10
Commit message: "update sleep time"
 > git rev-list --no-walk 26f9cd18d83485951213035c26aba7671df4f4b2 # timeout=10
[data-zhongguofeng] $ /bin/sh -xe /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/jenkins5288472147229753314.sh
+ python3 runner_qq.py --method search --query $'\344\270\255\345\233\275\351\243\216' --output-suffix zhongguofeng --dump-raw 1 --dump-seg 0 --proxy
INFO:[DataPipeline]:Start crawling for query: 中国风
INFO:[DataPipeline]:Processing playlist page: 0, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 1, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 2, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 3, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 4, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 5, found 47 playlists
INFO:[DataPipeline]:Processing playlist page: 6, found 47 playlists
INFO:[DataPipeline]:Processing playlist page: 7, found 45 playlists
INFO:[DataPipeline]:Processing playlist page: 8, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 9, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 10, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 11, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 12, found 44 playlists
INFO:[DataPipeline]:Processing playlist page: 13, found 43 playlists
INFO:[DataPipeline]:Processing playlist page: 14, found 44 playlists
INFO:[DataPipeline]:Processing playlist page: 15, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 16, found 41 playlists
INFO:[DataPipeline]:Processing playlist page: 17, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 18, found 46 playlists
INFO:[DataPipeline]:Processing playlist page: 19, found 46 playlists
INFO:[DataPipeline]:Processing playlist page: 20, found 41 playlists
INFO:[DataPipeline]:Processing playlist page: 21, found 46 playlists
INFO:[DataPipeline]:Processing playlist page: 22, found 42 playlists
INFO:[DataPipeline]:Processing playlist page: 23, found 43 playlists
INFO:[DataPipeline]:Processing playlist page: 24, found 20 playlists
INFO:[DataPipeline]:Processing playlist page: 25, found 18 playlists
INFO:[DataPipeline]:Processing playlist page: 26, found 21 playlists
INFO:[DataPipeline]:Processing playlist page: 27, found 20 playlists
INFO:[DataPipeline]:Processing playlist page: 28, found 21 playlists
INFO:[DataPipeline]:Processing playlist page: 29, found 21 playlists
INFO:[DataPipeline]:Processing playlist page: 30, found 19 playlists
INFO:[DataPipeline]:Processing playlist page: 31, found 21 playlists
INFO:[DataPipeline]:Processing playlist page: 32, found 21 playlists
INFO:[DataPipeline]:Processing playlist page: 33, found 18 playlists
INFO:[DataPipeline]:Processing playlist page: 34, found 17 playlists
INFO:[DataPipeline]:Processing playlist page: 35, found 21 playlists
INFO:[DataPipeline]:Processing playlist page: 36, found 18 playlists
INFO:[DataPipeline]:Processing playlist page: 37, found 21 playlists
INFO:[DataPipeline]:Processing playlist page: 38, found 16 playlists
INFO:[DataPipeline]:Processing playlist page: 39, found 29 playlists
INFO:[DataPipeline]:Processing playlist page: 40, found 21 playlists
INFO:[DataPipeline]:Processing playlist page: 41, found 21 playlists
INFO:[DataPipeline]:Processing playlist page: 42, found 19 playlists
INFO:[DataPipeline]:Processing playlist page: 43, found 21 playlists
INFO:[DataPipeline]:Processing playlist page: 44, found 21 playlists
INFO:[DataPipeline]:Processing playlist page: 45, found 21 playlists
INFO:[DataPipeline]:Processing playlist page: 46, found 30 playlists
INFO:[DataPipeline]:Processing playlist page: 47, found 20 playlists
INFO:[DataPipeline]:Processing playlist page: 48, found 20 playlists
INFO:[DataPipeline]:Processing playlist page: 49, found 19 playlists
INFO:[DataPipeline]:Processing playlist page: 50, found 0 playlists
INFO:[DataPipeline]:Total playlists found about topic: 中国风: 1644
INFO:[DataPipeline]:PlayList: [4247108355] 影视剧里的中国风对唱 (0/1644) has 68 songs.
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "/Library/Python/3.7/site-packages/urllib3/connection.py", line 308, in connect
    self._tunnel()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 911, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 502 Proxy Error: server_error Error creating ext request: timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Python/3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=215969338&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 502 Proxy Error: server_error Error creating ext request: timeout')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner_qq.py", line 60, in process_playlist
    lyric = api.get_song_lyric(song.id)
  File "/private/var/root/.jenkins/workspace/data-zhongguofeng/dao/qq_api.py", line 43, in get_song_lyric
    raw_text = self.fetch_raw(url)
  File "/private/var/root/.jenkins/workspace/data-zhongguofeng/dao/base_api.py", line 34, in fetch_raw
    verify=False)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=215969338&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 502 Proxy Error: server_error Error creating ext request: timeout')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "runner_qq.py", line 158, in <module>
    main()
  File "runner_qq.py", line 145, in main
    args.proxy, logger, args.dump_raw, args.dump_seg)
  File "runner_qq.py", line 70, in process_playlist
    logger.error("Exception in processing songs: ", err)
Message: 'Exception in processing songs: '
Arguments: (ProxyError(MaxRetryError("HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=215969338&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 502 Proxy Error: server_error Error creating ext request: timeout')))")),)
INFO:[DataPipeline]:PlayList: [7440131804] 100首影视歌曲，领悟中国风韵味 (1/1644) has 100 songs.
INFO:[DataPipeline]:PlayList: [4247123729] 影视剧里的中国风男声 (2/1644) has 88 songs.
INFO:[DataPipeline]:PlayList: [7328419661] 「中国风纯音」倚栏听风，如梦如醉 (3/1644) has 20 songs.
INFO:[DataPipeline]:PlayList: [7199774015] 中国风&#32;&#124;&#32;仙侠电视剧歌曲盘点 (4/1644) has 28 songs.
INFO:[DataPipeline]:PlayList: [7096063351] 影视剧中的中国风女声 (5/1644) has 96 songs.
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "/Library/Python/3.7/site-packages/urllib3/connection.py", line 360, in connect
    ssl_context=context,
  File "/Library/Python/3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Python/3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=104138207&_=1513437581324 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner_qq.py", line 60, in process_playlist
    lyric = api.get_song_lyric(song.id)
  File "/private/var/root/.jenkins/workspace/data-zhongguofeng/dao/qq_api.py", line 43, in get_song_lyric
    raw_text = self.fetch_raw(url)
  File "/private/var/root/.jenkins/workspace/data-zhongguofeng/dao/base_api.py", line 34, in fetch_raw
    verify=False)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=104138207&_=1513437581324 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "runner_qq.py", line 158, in <module>
    main()
  File "runner_qq.py", line 145, in main
    args.proxy, logger, args.dump_raw, args.dump_seg)
  File "runner_qq.py", line 70, in process_playlist
    logger.error("Exception in processing songs: ", err)
Message: 'Exception in processing songs: '
Arguments: (SSLError(MaxRetryError("HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=104138207&_=1513437581324 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1056)')))")),)
INFO:[DataPipeline]:PlayList: [7081812527] 中国风&#32;&#124;&#32;经典影视大全 (6/1644) has 64 songs.
INFO:[DataPipeline]:PlayList: [6966299000] 影视歌曲中的中国风 (7/1644) has 24 songs.
INFO:[DataPipeline]:PlayList: [7014439524] 中国风&#32;·&#32;何日君再来 (8/1644) has 33 songs.
INFO:[DataPipeline]:PlayList: [7166060330] 中国风代表作：一人一首经典曲 (9/1644) has 148 songs.
INFO:[DataPipeline]:Sleep for: 13
INFO:[DataPipeline]:PlayList: [6967276561] 抚琴煮茶，品一曲雅致中国风&#32; (10/1644) has 27 songs.
INFO:[DataPipeline]:PlayList: [6990664122] 抖音热播中国风音乐合集 (11/1644) has 24 songs.
INFO:[DataPipeline]:PlayList: [7233780688] 【中国风】宅家追古装剧必备 (12/1644) has 26 songs.
