Started by timer
Running as SYSTEM
Building in workspace /var/root/.jenkins/workspace/hot_user
using credential root
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@github.com:kirinisland/zaoci-tool.git # timeout=10
Fetching upstream changes from git@github.com:kirinisland/zaoci-tool.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git fetch --tags --force --progress -- git@github.com:kirinisland/zaoci-tool.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 2e2ff1f40957461f45e028fc94e151ca3f1a7c36 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 2e2ff1f40957461f45e028fc94e151ca3f1a7c36 # timeout=10
Commit message: "Merge pull request #1 from kirinisland/feature/test-logger"
 > git rev-list --no-walk 2e2ff1f40957461f45e028fc94e151ca3f1a7c36 # timeout=10
[hot_user] $ /bin/sh -xe /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/jenkins8681099472315959436.sh
+ python3 jobs/hot_user.py --count 25
Hot users after date: 2021-09-11 00:00:00
点赞最多: https://api2.bmob.cn/1/classes/EverydayLyric?&limit=25&where={"validStatus": {"$gte": 2, "$lte": 3}, "createdAt": {"$gte": {"__type": "Date", "iso": "2021-09-11 00:00:00"}}}&keys=user,likeCount,commentCount,bookmarkCount&order=-likeCount
[('d1725ff6a7', 10, 8, 0, 2), ('44789e844a', 12, 7, 0, 5), ('3f24a550f0', 11, 7, 2, 2), ('d5071c5734', 8, 7, 0, 1), ('3450fc1c98', 9, 5, 1, 3), ('c01956ae49', 8, 4, 0, 4), ('1b1e5d537a', 6, 3, 1, 2), ('95b5abf217', 8, 3, 2, 3), ('80fb0e9f90', 1, 1, 0, 0), ('47b7060a37', 1, 1, 0, 0), ('6db7ce0b74', 1, 1, 0, 0), ('f78bf9a628', 2, 1, 0, 1), ('8ec55b344b', 2, 1, 0, 1), ('95b5abf217', 0, 0, 0, 0), ('da9db94493', 0, 0, 0, 0), ('6db7ce0b74', 0, 0, 0, 0), ('af32cbcdd8', 0, 0, 0, 0), ('601c16c332', 0, 0, 0, 0), ('f3186cf176', 0, 0, 0, 0), ('2eb1b05567', 0, 0, 0, 0)]

评论最多: https://api2.bmob.cn/1/classes/EverydayLyric?&limit=25&where={"validStatus": {"$gte": 2, "$lte": 3}, "createdAt": {"$gte": {"__type": "Date", "iso": "2021-09-11 00:00:00"}}}&keys=user,likeCount,commentCount,bookmarkCount&order=-commentCount
[('3f24a550f0', 11, 7, 2, 2), ('95b5abf217', 8, 3, 2, 3), ('3450fc1c98', 9, 5, 1, 3), ('1b1e5d537a', 6, 3, 1, 2), ('80fb0e9f90', 1, 1, 0, 0), ('47b7060a37', 1, 1, 0, 0), ('c01956ae49', 8, 4, 0, 4), ('44789e844a', 12, 7, 0, 5), ('da9db94493', 0, 0, 0, 0), ('f78bf9a628', 2, 1, 0, 1), ('af32cbcdd8', 0, 0, 0, 0), ('601c16c332', 0, 0, 0, 0), ('8ec55b344b', 2, 1, 0, 1), ('f3186cf176', 0, 0, 0, 0), ('d1725ff6a7', 10, 8, 0, 2), ('d5071c5734', 8, 7, 0, 1), ('6db7ce0b74', 1, 1, 0, 0), ('6db7ce0b74', 0, 0, 0, 0), ('95b5abf217', 0, 0, 0, 0), ('2eb1b05567', 0, 0, 0, 0)]

收藏最多: https://api2.bmob.cn/1/classes/EverydayLyric?&limit=25&where={"validStatus": {"$gte": 2, "$lte": 3}, "createdAt": {"$gte": {"__type": "Date", "iso": "2021-09-11 00:00:00"}}}&keys=user,likeCount,commentCount,bookmarkCount&order=-bookmarkCount
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Library/Python/3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/Library/Python/3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/Library/Python/3.7/site-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/Library/Python/3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x10d703588>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Python/3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api2.bmob.cn', port=443): Max retries exceeded with url: /1/classes/EverydayLyric?&limit=25&where=%7B%22validStatus%22:%20%7B%22$gte%22:%202,%20%22$lte%22:%203%7D,%20%22createdAt%22:%20%7B%22$gte%22:%20%7B%22__type%22:%20%22Date%22,%20%22iso%22:%20%222021-09-11%2000:00:00%22%7D%7D%7D&keys=user,likeCount,commentCount,bookmarkCount&order=-bookmarkCount (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10d703588>: Failed to establish a new connection: [Errno 60] Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jobs/hot_user.py", line 170, in <module>
    main()
  File "jobs/hot_user.py", line 98, in main
    bookmark_most_users = fetch_hot_users(bookmark_url, headers)
  File "jobs/hot_user.py", line 113, in fetch_hot_users
    raw = requests.get(url, headers=headers)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api2.bmob.cn', port=443): Max retries exceeded with url: /1/classes/EverydayLyric?&limit=25&where=%7B%22validStatus%22:%20%7B%22$gte%22:%202,%20%22$lte%22:%203%7D,%20%22createdAt%22:%20%7B%22$gte%22:%20%7B%22__type%22:%20%22Date%22,%20%22iso%22:%20%222021-09-11%2000:00:00%22%7D%7D%7D&keys=user,likeCount,commentCount,bookmarkCount&order=-bookmarkCount (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10d703588>: Failed to establish a new connection: [Errno 60] Operation timed out'))
Build step 'Execute shell' marked build as failure
Finished: FAILURE
